### PR TITLE
package: don't disable testsuites on qemu build

### PR DESCRIPTION
**Pull request by andreas-schwab**

### CODE REVIEW

**Comment by dgdavid** [comment]
Hi @andreas-schwab 

First of all, sorry for overlooking this until now. 

Could you please provide the rationale of the proposed change. Why t's needed to enable back these testsuite on qemu build?

**Comment by andreas-schwab** [comment]
It's no longer needed.

**Comment by dgdavid** [comment]
Ok, thanks for the input.

**Comment by andreas-schwab** [comment]
WTF?

**Comment by dgdavid** [comment]
> WTF?

A misunderstanding from my side, I guess.

I asked you for a rationale about why it's needed to enable back the testsuite on qemu build and you simply asked

> It's no longer needed.

Which I interpreted as _The PR it's no longer needed_

Please, elaborate a bit more your answer in order to move on the PR.

Thanks

**Comment by dgdavid** [comment]
Reopening since it looks like the author still interested.

**Comment by andreas-schwab** [comment]
It's simply obsolete.

**Pull request closed without merging**
