### PR TITLE
add configure-option '--disable-debug'

### PR DESCRIPTION
**Pull request by besser82**
As the title says.  There is no change in default behaviour. I just added an option to include "-DNDEBUG" by configure-switch in addtion to pass it from $ENV's C(XX)FLAGS.

### CODE REVIEW

**Comment by besser82** [comment]
Please merge https://github.com/yast/yast-devtools/pull/87 *before* this one and wait for me to rebase this onto new master.

**Comment by besser82** [comment]
Allrighty…  Rebased onto recent master.  Ready for merging.

**Comment by mvidner** [comment]
Looks good, thanks!

**Comment by besser82** [comment]
Fine…  Thanks you, Martin! :D

**Pull request merged**
